### ISSUE TITLE
Is there a way to increase the height of the spinner area?

### ISSUE THREAD

**Issue by harryworld** [adib/RefreshableScrollView#1]
It has the elasticity to scroll. When I scroll naturally, it moves around 20 points. In your implementation it needs about 33 points for the spinner to happen.

Is there a way to move a wider range with the same scrolling speed?

**Comment by adib** [comment]
The height is really determined by the spinner's compression resistance. To make it larger or smaller, add a height constraint to the progress indicator and lower its compression resistance. You can do this by overriding `topProgressIndicator` or `bottomProgressIndicator` and make the appropriate changes.
